### ISSUE TITLE
Error in Custom Timer Trigger

### ISSUE THREAD

**Issue by arnigunnar** [Azure/azure-webjobs-sdk-extensions#12]
I tried to set up a custom TimerTrigger yesterday with the alpha2 SDK. This is my setup, should run every day at 2AM:

	public static async void EmailRuleSender([TimerTrigger(typeof(EmailRuleScheduler))] TimerInfo info) {
		// STUFF ...
	}
	public class EmailRuleScheduler : DailySchedule {
		public EmailRuleScheduler() : base("2:00:00") { }
	}

This results in this error:

[09/15/2015 21:57:40 > fdcfbe: INFO] Executed: 'Functions.EmailRuleSender' (Succeeded)
[09/15/2015 21:57:40 > fdcfbe: ERR ] 
[09/15/2015 21:57:40 > fdcfbe: ERR ] Unhandled Exception: System.ArgumentException: '-71860628.1954' is not a valid value for 'Interval'. 'Interval' must be greater than 0.
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Timers.Timer.set_Interval(Double value)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Extensions.Timers.Listeners.TimerListener.StartTimer(TimeSpan interval)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Extensions.Timers.Listeners.TimerListener.<StartAsync>d__1.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Host.Listeners.SingletonListener.<StartAsync>d__0.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__0.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__0.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.<StartAsyncCore>d__0.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Host.Listeners.HeartbeatListener.<StartAsync>d__0.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.<StartAsync>d__0.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__0.MoveNext()
[09/15/2015 21:57:40 > fdcfbe: ERR ] --- End of stack trace from previous location where exception was thrown ---
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
[09/15/2015 21:57:40 > fdcfbe: ERR ]    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
[09/15/2015 21:57:41 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.JobHost.Start()
[09/15/2015 21:57:41 > fdcfbe: ERR ]    at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
[09/15/2015 21:57:41 > fdcfbe: ERR ]    at SystemQueueListener.Program.Main()
[09/15/2015 21:57:41 > fdcfbe: SYS ERR ] Job failed due to exit code -532462766
[09/15/2015 21:57:41 > fdcfbe: SYS INFO] Process went down, waiting for 60 seconds

**Comment by mathewc** [comment]
We'll repro and fix ASAP. As a workaround until then, you can use a crontab expression to achieve your schedule. E.g. "0 0 2 * * *"

**Comment by mathewc** [comment]
FYI - We've fixed this bug (commit https://github.com/Azure/azure-webjobs-sdk-extensions/commit/59791fb15699d93ce987650ca51cfe4838c878b0), and got this into the beta1 release that we just wrapped up this morning. The new beta1 Extensions package should be live on nuget shortly.

Also note that we've added the ability to log the next N occurrences of your schedule for debugging purposes (see TimerInfo.FormatNextOccurrences). Also, by default if JobHostConfiguration.Tracing.ConsoleLevel is set to Verbose, we'll automatically log to console the next 5 occurrences for each function.

**Comment by arnigunnar** [comment]
Sweeeet ... :+1:

**Comment by mathewc** [comment]
FYI - beta1 is live now on Nuget :) Thanks for reporting the issue.

**Comment by arnigunnar** [comment]
I can confirm that this is indeed fixed in beta1, just ran this on my webjob at 2AM last night:

[09/17/2015 02:00:00 > fdcfbe: INFO] Executing: 'Functions.EmailRuleSender' - Reason: 'Timer fired at 2015-09-17T02:00:00.9058977Z'
[09/17/2015 02:00:01 > fdcfbe: INFO] Executed: 'Functions.EmailRuleSender' (Succeeded)

Thanks for the quick response ... :+1:

**Comment by mathewc** [comment]
Thanks. What are you using to send your emails in your job funciton? We recently added a SendGrid binder for sending emails - might be useful to you.

**Comment by arnigunnar** [comment]
We are using Mandrill, an app built by MailChimp. We used to use SendGrid, but Mandrill is a lot cheaper and more stable.
