### ISSUE TITLE
CosmosDBTrigger changefeed not supported with Tables API on v1 runtime

### ISSUE THREAD

**Issue by johlrich** [Azure/azure-webjobs-sdk-extensions#341]
Version of change processor + documentdb client is likely out of date wrt support for the TablesAPI.

#### Repro steps

Create CosmosDB database with Table API and azure trigger function trigger to a collection on it.

#### Expected behavior

Change function gets triggered for changes to any row.

#### Actual behavior

Nothing triggered. Locally you can see exceptions in the debug from the change feed processor saying the collection was made with a newer sdk than the one being used.

Debug output snippet:
```
DocDBTrace Error: 0 : DocumentClientException with status code BadRequest, message: Message: {"Errors":["The collection cannot be accessed with this SDK version as it was created with newer SDK version."]}, inner exception: null, and response headers: {
"x-ms-last-state-change-utc": "Thu, 30 Nov 2017 04:10:22.661 GMT",
"lsn": "7",
"x-ms-schemaversion": "1.3",
"x-ms-documentdb-partitionkeyrangeid": "0",
"x-ms-xp-role": "2",
"x-ms-request-charge": "0",
"x-ms-serviceversion": " version=1.17.101.1",
"x-ms-activity-id": "cc149a61-c04d-413a-94f8-975f2fb80709",
}
DocDBTrace Information: 0 : Exception Microsoft.Azure.Documents.BadRequestException: Message: {"Errors":["The collection cannot be accessed with this SDK version as it was created with newer SDK version."]}
ActivityId: cc149a61-c04d-413a-94f8-975f2fb80709, Request URI: rntbd://bl4prdddc02-docdb-2.documents.azure.com:14174/apps/1240113d-9858-49b9-90cb-1219f9e1df77/services/cf6d32ff-1425-4f0f-827b-42ada42e368b/partitions/077fb0bc-a16c-4b8f-a7e7-28c756793a03/replicas/131564886124676907s/
   at Microsoft.Azure.Documents.RntbdTransportClient.ThrowIfFailed(String resourceAddress, StoreResponse storeResponse, Uri physicalAddress, Guid activityId)
   at Microsoft.Azure.Documents.RntbdTransportClient.<InvokeStoreAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

Upgrading packages worked on a standalone console app for this scenario.

#### Known workarounds

None for people on a consumption plan.
Upgrade package to latest changefeedprocessor + documentdb client to work otherwise.

#### Related information 

v1 runtime

**Comment by brettsam** [comment]
@ealsur -- did we discuss this already? I can't remember the exact limitation...

**Comment by ealsur** [comment]
The idea was to eventually add compatibility with all API types to use `IReadOnlyList<Row>` (or something similar for Tables) and another type for Graph. But this one seems to be a block on the server side with the client version.

**Comment by ealsur** [comment]
@brettsam after verifying with SDK team, SDK version needs to be `1.19.0` or higher for Tables accounts.

**Comment by ealsur** [comment]
This should work on V2 since the SDK there is 1.20.2.
