### ISSUE TITLE
Azure Function - Goes Offline

### ISSUE THREAD

**Issue by alohaninja** [Azure/azure-webjobs-sdk-extensions#355]
Our Azure Function went offline (_stopped processing queue messages_) with the error message below - despite the site (`w3wp.exe`) still being available/pingable. We are using latest 2.0.11415.0 (beta) azure function runtime with javascript language. The input trigger is an Azure Message Queue. Messages are still in the `process` queue and they are not being picked up. 

### Azure Function - Failure Message
`An unexpected network error occurred`

Hoping someone has an idea why this happened. 

### Workaround
For now it seems restarting the function app corrects the function offline issue. Noticed that 10 or so messages in the `process` queue had a dequeue count anywhere from 20-60. Our `host.json` is configured with `maxDequeueCount=1`, so not sure what's going on here. 

Also noticing that our S1 instance is processing 2 messages concurrently even though we have `batchSize=1` and `newBatchThreshold=1` in our `host.json` file.

**Comment by alohaninja** [comment]
Here is the failure output from App Insights logs...

### Azure Function IOException Failure
System.IO.IOException:
   at System.ConsolePal+WindowsConsoleStream.Write (System.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.StreamWriter.Flush (System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.StreamWriter.WriteLine (System.Runtime.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.IO.SyncTextWriter.WriteLine (System.Console, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.InvokeTextWriter (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\CompositeTraceWriter.cs: 75)
   at Microsoft.Azure.WebJobs.Host.ConsoleTraceWriter.InvokeTextWriter (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\ConsoleTraceWriter.cs: 44)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.Trace (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\CompositeTraceWriter.cs: 46)
   at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.Trace (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\TraceWriterFunctionInstanceLogger.cs: 57)
   at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.LogFunctionStartedAsync (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\TraceWriterFunctionInstanceLogger.cs: 29)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.LogFunctionStartedAsync (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs: 423)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<ExecuteWithLoggingAsync>d__16.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs: 253)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult (System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e)
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor+<TryExecuteAsync>d__13.MoveNext (Microsoft.Azure.WebJobs.Host, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null: C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs: 96)

**Comment by brettsam** [comment]
It's possible that your host has crashed due to this error. This callstack has changed (we no longer use `CompositeTraceWriter`, for example), but those changes have not yet been released. I'm going to close this -- but please let us know if you continue to see the issue.

**Comment by alohaninja** [comment]
@brettsam our function app host just crashed early this morning with this same error. Any ideas when the latest changes will be published? Still seeing the same problem with our azure function. 

When this happens, the only resolution is to restart the function app as it gets into a stuck state and won't process any events. 

### Azure Function - An unexpected network error occurred

```
2018-01-24T14:03:54.357 An unhandled exception has occurred. Host is shutting down.
2018-01-24T14:03:54.375 System.IO.IOException : An unexpected network error occurred
   at System.ConsolePal.WindowsConsoleStream.Write(Byte[] buffer,Int32 offset,Int32 count)
   at System.IO.StreamWriter.Flush(Boolean flushStream,Boolean flushEncoder)
   at System.IO.StreamWriter.WriteLine(String value)
   at System.IO.SyncTextWriter.WriteLine(String value)
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.InvokeTextWriter(TraceEvent traceEvent) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\CompositeTraceWriter.cs : 75
   at Microsoft.Azure.WebJobs.Host.ConsoleTraceWriter.InvokeTextWriter(TraceEvent traceEvent) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\ConsoleTraceWriter.cs : 44
   at Microsoft.Azure.WebJobs.Host.CompositeTraceWriter.Trace(TraceEvent traceEvent) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\CompositeTraceWriter.cs : 46
   at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.Trace(TraceLevel level,Guid hostInstanceId,FunctionDescriptor descriptor,Guid functionId,String message,String source,Exception exception) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\TraceWriterFunctionInstanceLogger.cs : 57
   at Microsoft.Azure.WebJobs.Host.Loggers.TraceWriterFunctionInstanceLogger.LogFunctionCompletedAsync(FunctionCompletedMessage message,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Loggers\TraceWriterFunctionInstanceLogger.cs : 43
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 142
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.TriggeredFunctionExecutor`1.TryExecuteAsync[TTriggerValue](TriggeredFunctionData input,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\TriggeredFunctionExecutor.cs : 54
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueTriggerExecutor.ExecuteAsync(IStorageQueueMessage value,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Queues\Listeners\QueueTriggerExecutor.cs : 30
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Queues.Listeners.QueueListener.ProcessMessageAsync(IStorageQueueMessage message,TimeSpan visibilityTimeout,CancellationToken cancellationToken) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Queues\Listeners\QueueListener.cs : 262
```
