### ISSUE TITLE
[CosmosDBTrigger] If Stop() is called before Start(), the trigger can throw an exception

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-extensions#379]
During testing of something unrelated, I saw a stack with:

```
   at Microsoft.Azure.Documents.ChangeFeedProcessor.ChangeFeedEventHost.<StopAsync>d__7a.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Documents.ChangeFeedProcessor.ChangeFeedEventHost.<UnregisterObserversAsync>d__6.MoveNext()
```

I think it's happening b/c the host is calling Start/Stop very quickly, which means that Stop is actually being called first. It looks like internally the ChangeFeedProcessor may throw in that case. We should either catch that  and ignore it, or check if it's able to be Unregistered (if that's possible).

**Comment by brettsam** [comment]
@ealsur -- any ideas on this?

**Comment by ealsur** [comment]
That's weird, do you happen to have the entire stack trace? Any way I can repro the scenario?

**Comment by brettsam** [comment]
That's the only stack that showed up -- I wonder if you created a new `CosmosDBListener()` and called `Stop()` immediately on it (without calling `Start()` first).

**Comment by ealsur** [comment]
That should throw I think, because there is no observer to unregister.

**Comment by brettsam** [comment]
It's probably very rare, but we should make sure that doesn't throw.  I was doing some crazy Start/Stop testing when I saw it. There's a possibility that while we're looping and starting all Listeners that Stop gets called immediately, before Start has been called on the Listener.

**Comment by ealsur** [comment]
👍 I'll wrap it and log the exception, sounds good?
