### ISSUE TITLE
twilioSms output bindings form creates incorrect key names

### ISSUE THREAD

**Issue by gopuff** [Azure/azure-webjobs-sdk-extensions#385]
#### Repro steps

Using runtime 1.x

Create a new output binding of twilioSms.
Enter An AccountSID and AuthToken
view the created json using the advanced editor

It creates 
``` 
 {
      "type": "twilioSms",
      "name": "message",
      "accountSid": "XXXXXXX",
      "authToken":  "XXXXXXX"
```

#### Expected behavior

  Using the standard editor should result in an SMS being sent. 

#### Actual behavior

  The function throws a stacktrace

```
Exception while executing function: Functions.sendSms
Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.sendSms ---> System.InvalidOperationException : Unable to resolve app setting for property 'TwilioSmsAttribute.AccountSidSetting'. Make sure the app setting exists and has a valid value.
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.GetAppSettingResolver(String originalValue,AppSettingAttribute attr,INameResolver nameResolver,PropertyInfo propInfo,Action`1 validator)
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.GetResolver(PropertyInfo propInfo,INameResolver nameResolver,IReadOnlyDictionary`2 contract)
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1.<>c__DisplayClass6_0.<.ctor>b__8(PropertyInfo prop)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Azure.WebJobs.Host.Bindings.AttributeCloner`1..ctor(TAttribute source,IReadOnlyDictionary`2 bindingDataContract,INameResolver nameResolver)
   at async Microsoft.Azure.WebJobs.Host.Bindings.GenericCompositeBindingProvider`1.TryCreateAsync[TAttribute](BindingProviderContext context)
   at async Microsoft.Azure.WebJobs.Host.Bindings.CompositeBindingProvider.TryCreateAsync(BindingProviderContext context)
   at async Microsoft.Azure.WebJobs.Binder.BindAsync[TValue](??)
   at async Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.BindAsyncCollectorAsync[T](BindingContext context) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Binding\FunctionBinding.cs : 0
   at async Microsoft.Azure.WebJobs.Script.Binding.ExtensionBinding.BindAsync(BindingContext context) at C:\projects\azure-webjobs-sdk-script\src\WebJobs.Script\Binding\ExtensionBinding.cs : 55
```

#### Known workarounds

This setting does not work.
Changing the ```functions.json``` to
```
 {
      "type": "twilioSms",
      "name": "message",
      "AccountSidSetting": "XXXXXXXX",
      "AuthTokenSetting": "XXXXXX"
```
works 

#### Related information 

I guess this could also be fixed by changing the key names in the code.  I'm not sure what is the right fix.

**Comment by paulbatum** [comment]
Please see this tutorial: https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-twilio

You need to put the name of app settings in, rather than the actual id/token.
