### ISSUE TITLE
Sample TimerSamples.StartupJob is not working

### ISSUE THREAD

**Issue by alincosmin7** [Azure/azure-webjobs-sdk-extensions#529]
I disabled all other triggers and keep only TimerSamples class.
When start the sample I get these errors in logs, but only for StartupJob

dbug: Microsoft.Extensions.Hosting.Internal.Host[1]
      Hosting starting
info: Microsoft.Azure.WebJobs.Hosting.JobHostService[0]
      Starting JobHost
info: Host.Startup[0]
      Found the following functions:
      WebJobsSandbox.TimerSamples.CronJob
      WebJobsSandbox.TimerSamples.StartupJob
      WebJobsSandbox.TimerSamples.TimerJob
      WebJobsSandbox.TimerSamples.WeeklyTimerJob

dbug: Host.Singleton[0]
      Singleton lock acquired (cead61-62cf-47f4-93b4-6efcded6/WebJobsSandbox.TimerSamples.CronJob.Listener)
info: Host.Triggers.Timer[0]
      The next 5 occurrences of the schedule will be:
      10/29/2018 11:38:15 PM
      10/29/2018 11:38:30 PM
      10/29/2018 11:38:45 PM
      10/29/2018 11:39:00 PM
      10/29/2018 11:39:15 PM

dbug: Host.Singleton[0]
      Singleton lock acquired (cead61-62cf-47f4-93b4-6efcded6/WebJobsSandbox.TimerSamples.StartupJob.Listener)
fail: Host.Startup[0]
      The listener for function 'TimerSamples.StartupJob' was unable to start.
Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException: The listener for function 'TimerSamples.StartupJob' was unable to start. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at Microsoft.WindowsAzure.Storage.CloudStorageAccount.Parse(String connectionString) in C:\Program Files (x86)\Jenkins\workspace\release_dotnet_master\Lib\Common\CloudStorageAccount.cs:line 524
   at Microsoft.Azure.WebJobs.Extensions.Timers.StorageScheduleMonitor.get_TimerStatusDirectory() in C:\Users\MyUser\Downloads\azure-webjobs-sdk-extensions-master\src\WebJobs.Extensions\Extensions\Timers\Scheduling\StorageScheduleMonitor.cs:line 78

**Comment by mathewc** [comment]
The error is happening because you don't have a storage account configured. The error message should be improved. TimerTrigger by default leverages storage for singleton locks. Can you provide a storage account connection and try again?

**Comment by SeboStone** [comment]
I have the same issue in my own implementation and I want to configure the Azure Storage Connection, but how? I did not found any documentation to do that with the new version 2.2 and the AddAzureStorage() method have not a parameter to add a connectionstring. Can you help me?

**Comment by SeboStone** [comment]
Ok, I found it in ths post: https://github.com/Azure/azure-webjobs-sdk/issues/1963#issue-370375542
But seriously, what is this magic? I think at least an additional programmatically way is necessary.

**Comment by mathewc** [comment]
In v3 there isn't a top level config property for the storage account connection string. You need to provide the connection via .NET Core configuration (appsettings.json) or via an environment variable.

Agree that we need to improve the error handling here.

**Comment by tuanfred** [comment]
What's happen if i do not use appsetting.json (because i use yaml format) ? API should not force to use appseting.json, pls

**Comment by cyptus** [comment]
watch out if you add `appsettings.json` file and use it with `.ConfigureAppConfiguration(x => x.AddJsonFile("appsettings.json"))` that you set the files `Copy to Output Directory` in visual studio to `Copy always`

@tuanfred you can add settings from whatever source you want. instead of `AddJsonFile` you can for example use enviroment variables or custom setting providers

**Comment by markmcgookin** [comment]
I'm getting this exact error with a 3.1 Timer Trigger Webjob... but I have a valid connection string in there (that I am using in other service bus triggered webjobs) the line before I call host.run I check with `config.GetConnectionString("AzureWebJobsStorage")` and it comes back with the correct result... not sure what I am doing wrong here.

![image](https://user-images.githubusercontent.com/1053345/69814901-1b3b1680-11ed-11ea-8056-f0d671cc88a9.png)

**Comment by FrankSzendzielarz** [comment]
@cyptus  Good grief. Thanks for that. Like looking for a needle in a field of haystacks.
