### ISSUE TITLE
HttpTrigger issues in production 3.0.14111 and 2.0.14048

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-webjobs-sdk-extensions#655]
Exception is -- 
```
System.NotSupportedException : Specified method is not supported.
   at Microsoft.AspNetCore.Server.IIS.Core.ReadOnlyStream.set_Position(Int64 value)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.set_Position(Int64 value)
```

The issue is with any requests that have content and the content-type header is not explicitly application/json
 
v2:
- Cannot seek the request body in a C# app
- Out-of-proc languages fail.
v3:
- Cannot seek the request body in a C# app

**Comment by pragnagopa** [comment]
Failure for out-of-proc have following trace:

```
System.NotSupportedException : Specified method is not supported.
   at Microsoft.AspNetCore.Server.IIS.Core.ReadOnlyStream.set_Position(Int64 value)
   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.set_Position(Int64 value)
   at Microsoft.Azure.WebJobs.Script.Extensions.HttpRequestExtensions.GetRequestBodyAsBytes(HttpRequest request) at D:\a\1\s\src\WebJobs.Script\Extensions\HttpRequestExtensions.cs : 98
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcMessageConversionExtensions.PopulateBody(HttpRequest request,RpcHttp http,Capabilities capabilities,ILogger logger) at D:\a\1\s\src\WebJobs.Script\Workers\Rpc\MessageExtensions\RpcMessageConversionExtensions.cs : 207
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcMessageConversionExtensions.ToRpcHttp(HttpRequest request,ILogger logger,Capabilities capabilities) at D:\a\1\s\src\WebJobs.Script\Workers\Rpc\MessageExtensions\RpcMessageConversionExtensions.cs : 194
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcMessageConversionExtensions.ToRpc(Object value,ILogger logger,Capabilities capabilities) at D:\a\1\s\src\WebJobs.Script\Workers\Rpc\MessageExtensions\RpcMessageConversionExtensions.cs : 77
   at Microsoft.Azure.WebJobs.Script.Workers.ScriptInvocationContextExtensions.ToRpcInvocationRequest(ScriptInvocationContext context,Boolean isTriggerMetadataPopulatedByWorker,ILogger logger,Capabilities capabilities) at D:\a\1\s\src\WebJobs.Script\Workers\MessageExtensions\ScriptInvocationContextExtensions.cs : 44
   at Microsoft.Azure.WebJobs.Script.Workers.Rpc.RpcWorkerChannel.SendInvocationRequest(ScriptInvocationContext context) at D:\a\1\s\src\WebJobs.Script\Workers\Rpc\RpcWorkerChannel.cs : 326
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.WorkerFunctionInvoker.InvokeCore(Object[] parameters,FunctionInvocationContext context) at D:\a\1\s\src\WebJobs.Script\Description\Workers\WorkerFunctionInvoker.cs : 85
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionInvokerBase.Invoke(Object[] parameters) at D:\a\1\s\src\WebJobs.Script\Description\FunctionInvokerBase.cs : 85
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Script.Description.FunctionGenerator.Coerce[T](Task`1 src) at D:\a\1\s\src\WebJobs.Script\Description\FunctionGenerator.cs : 225
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.InvokeAsync[TReflected,TReturnValue](Object instance,Object[] arguments) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs : 52
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.InvokeAsync(IFunctionInvoker invoker,ParameterHelper parameterHelper,CancellationTokenSource timeoutTokenSource,CancellationTokenSource functionCancellationTokenSource,Boolean throwOnTimeout,TimeSpan timerInterval,IFunctionInstance instance) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 568
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance,ParameterHelper parameterHelper,ILogger logger,CancellationTokenSource functionCancellationTokenSource) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 514
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 460
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(??) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs : 270
```
