### ISSUE TITLE
TaskCanceledException thrown from http trigger with queue output

### ISSUE THREAD

**Issue by ThomasBleijendaal** [Azure/azure-webjobs-sdk-extensions#744]
A TaskCanceledException was thrown from a http trigger function which should directly output to a queue. It looks like http connection pool was in trouble as every request caused an instant TaskCanceledException and we could only resolve this issue with a reboot of the function app service.

The http trigger function is implemented as follows:

```c#
[FunctionName(nameof(CancelBookingAsync))]
[return: Queue("async-cancel-booking")]
public async Task<string> CancelBookingAsync(
    [HttpTrigger(AuthorizationLevel.Function, "POST", Route = "cancel")]
    [RequestBodyType(typeof(ReservationExternalSystemModel), "body")]
    HttpRequest request)
{
    using var bodyReader = new StreamReader(request.Body, encoding: Encoding.UTF8);
    return await bodyReader.ReadToEndAsync();
}
```

The function app is running in an EP1 App Service Plan.

#### Repro steps

We've tried to reproduce the issue with adding some load to another function app but could not reproduce the issue.

#### Expected behavior

The function should add the request body as queue message to the associated storage queue.

#### Actual behavior

The function threw TaskCanceledException and 500 Internal Server Errors until rebooted.

#### Known workarounds

Reboot the function app.

#### Related information 

Provide any related information 

* Package version: 

```xml
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="2.5.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="3.0.10" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.13" />
```

* Links to source

Log messages (new to old)

```
20 Sep 2021 10:07:18.038
Executed 'CancelBookingAsync' (Failed, Id=b7c27d1a-31c2-489f-870d-49fee3512218, Duration=2ms)
20 Sep 2021 10:07:18.038
Executing 'CancelBookingAsync' (Reason='This function was programmatically called via the host APIs.', Id=b7c27d1a-31c2-489f-870d-49fee3512218)
20 Sep 2021 10:07:18.038
Requesting cancellation for function invocation 'b7c27d1a-31c2-489f-870d-49fee3512218' 
```

Stacktrace:
```
Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: CancelBookingAsync

 ---> System.InvalidOperationException: Error while handling parameter $return after function returned:

 ---> Microsoft.WindowsAzure.Storage.StorageException: A task was canceled.

 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)

   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)

   --- End of inner exception stack trace ---

   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteAsyncInternal[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)

   at Microsoft.Azure.WebJobs.Host.Queues.StorageQueueExtensions.AddMessageAndCreateIfNotExistsAsync(CloudQueue queue, CloudQueueMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\StorageQueueExtensions.cs:line 27

   at Microsoft.Azure.WebJobs.Host.Queues.Config.QueuesExtensionConfigProvider.QueueAsyncCollector.AddAsync(CloudQueueMessage message, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Extensions.Storage\Queues\Config\QueuesExtensionConfigProvider.cs:line 254

   at Microsoft.Azure.WebJobs.Host.Bindings.TypedAsyncCollectorAdapter`3.AddAsync(TSrc item, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AsyncCollector\TypedAsyncCollectorAdapter.cs:line 40

   at Microsoft.Azure.WebJobs.Host.Bindings.OutValueProvider`1.SetValueAsync(Object value, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AsyncCollector\OutValueProvider.cs:line 52

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.ProcessOutputParameters(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 942

Request Information

RequestID:

RequestDate:

StatusMessage:

ErrorCode:



   --- End of inner exception stack trace ---

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.ProcessOutputParameters(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 952

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 535

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 296

   --- End of inner exception stack trace ---

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343

   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105

   at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ExceptionDispatchInfoDelayedException.cs:line 28

   at Microsoft.Azure.WebJobs.JobHost.CallAsyncCore(IFunctionDefinition function, Object functionKey, IDictionary`2 arguments, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 241

   at Microsoft.Azure.WebJobs.JobHost.CallAsync(String name, IDictionary`2 arguments, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 225

   at Microsoft.Azure.WebJobs.Script.WebHost.Features.FunctionExecutionFeature.ExecuteAsync(HttpRequest request, CancellationToken cancellationToken) in D:\a\1\s\src\WebJobs.Script.WebHost\Features\FunctionExecutionFeature.cs:line 76

   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.GetResultAsync(HttpContext context, IFunctionExecutionFeature functionExecution) in D:\a\1\s\src\WebJobs.Script.WebHost\Middleware\FunctionInvocationMiddleware.cs:line 127

   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.FunctionInvocationMiddleware.Invoke(HttpContext context) in D:\a\1\s\src\WebJobs.Script.WebHost\Middleware\FunctionInvocationMiddleware.cs:line 47

   at Microsoft.Azure.WebJobs.Script.WebHost.Middleware.ExceptionMiddleware.Invoke(HttpContext context) in D:\a\1\s\src\WebJobs.Script.WebHost\Middleware\ExceptionMiddleware.cs:line 27
```

**Comment by v-anvari** [comment]
Hi @ThomasBleijendaal , Thank you for making us aware of such occurrence. It could be a server side error which would have been fixed with a refresh. Do let us know if you see the issue again, so that we can investigate further
