### ISSUE TITLE
Cosmos DB Trigger Can't Find App Setting for Connection String .net6

### ISSUE THREAD

**Issue by tottes200** [Azure/azure-webjobs-sdk-extensions#748]
Cosmos DB trigger failing to retrieve app setting in Azure. When running locally with an environment variable set on the machine this works fine. When publishing to Azure this

.net6 RC2
Azure Functions v4

#### Repro steps

Provide the steps required to reproduce the problem

1. Create CosmosDbTrigger function
2. Publish to Azure Functions App, wait for error.

#### Expected behavior

Trigger should pick up connection string from App Settings and function should be indexed.

#### Actual behavior

Trigger fails, stating app setting does not exist. Function fails to load

#### Related information 

Error message from Azure logs:

```
2021-10-17T21:03:29.094 [Error] Error indexing method 'SendJobsUpdatedNotification'Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException : Error indexing method 'SendJobsUpdatedNotification' ---> System.InvalidOperationException : Cannot create container information for JobProgress in database Zeus with lease Leases_JobProgress in database Zeus : Cosmos DB connection configuration 'CosmosDBConnection' does not exist. Make sure that it is a defined App Setting. ---> System.InvalidOperationException : Cosmos DB connection configuration 'CosmosDBConnection' does not exist. Make sure th
   at it is a defined App Setting.at Microsoft.Azure.WebJobs.Extensions.CosmosDB.DefaultCosmosDBServiceFactory.ResolveConnectionInformation(String connection) at C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\DefaultCosmosDBServiceFactory.cs : 45
   at Microsoft.Azure.WebJobs.Extensions.CosmosDB.DefaultCosmosDBServiceFactory.CreateService(String connectionName,CosmosClientOptions) at C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\DefaultCosmosDBServiceFactory.cs : 27
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key,Func`2)
   at Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBExtensionConfigProvider.GetService(String connection,String) at C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\CosmosDBExtensionConfigProvider.cs : 108
   at async Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBTriggerAttributeBindingProvider`1.TryCreateAsync[T](TriggerBindingProviderContext context) at C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Trigger\CosmosDBTriggerAttributeBindingProvider.cs : 81End of inner exception
   at async Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBTriggerAttributeBindingProvider`1.TryCreateAsync[T](TriggerBindingProviderContext context) at C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Trigger\CosmosDBTriggerAttributeBindingProvider.cs : 107
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs : 22
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method,IFunctionIndexCollector) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 172
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 149End of inner exception
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method,IFunctionIndexCollector) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 157
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type,IFunctionIndexCollector) at C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs : 85
```

Microsoft.Azure.WebJobs 3.0.30
Microsoft.Azure.WebJobs.Extensions 4.0.1
Microsoft.Azure.WebJobs.Extensions.CosmosDB 4.0.0-preview2

Screenshot of App Setting
<img width="538" alt="2021-10-17_17h16_06" src="https://user-images.githubusercontent.com/44611315/137645314-2feb6abd-436c-432d-b564-05341b560c91.png">

**Comment by tottes200** [comment]
I have fixed this. Apparently you must set this as a connection string now and not an app Setting. See below. This fixed the issue.

<img width="1353" alt="2021-10-17_17h44_02" src="https://user-images.githubusercontent.com/44611315/137646054-9ece4999-2ffd-4f6b-b718-6eea903595d2.png">

I believe the documentation should be updated to reflect these changes, unless it has been and I somehow missed it.

**Comment by v-anvari** [comment]
Thank you for the feedback, we will surely update this scenario to the docs team. Can we have the docs link in case you have any link that  you are specifying to

**Comment by ealsur** [comment]
@tottes200 thanks for the report, I was able to identify the issue and send a PR to fix it on the current preview code

**Comment by tottes200** [comment]
Thank you sir!

**Comment by ealsur** [comment]
This is part of the preview3 release
