### ISSUE TITLE
CosmosDB trigger 4.x fails to resolve trigger attributes (connection, databasename and containername)

### ISSUE THREAD

**Issue by arafeeq21** [Azure/azure-webjobs-sdk-extensions#823]
We're attempting to deploy the Azure function based Cosmos DB trigger to Kubernetes; it throws an exception and doesn't resolve the trigger attributes.

In order to setup the CosmosDB trigger attributes namely: 
Connection, databaseName and containerName we use appsettings.json to specify the values. The settings are initialized via helm chart using ENV values that override appsettings.

The web job fails to resolve the settings at start up in the deployment step and we encounter the following error - 
`fail: Host.Startup[0]
      Error indexing method 'AdmEntitiesCosmosDBTrigger'
      Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'AdmEntitiesCosmosDBTrigger'
       ---> System.InvalidOperationException: Cannot create container information for %ContainerName% in database %Database% with lease leases in database %Database% : Connection should have an 'accountEndpoint' property or be a string representing a connection string.
       ---> System.InvalidOperationException: Connection should have an 'accountEndpoint' property or be a string representing a connection string.
         at Microsoft.Azure.WebJobs.Extensions.CosmosDB.DefaultCosmosDBServiceFactory.ResolveConnectionInformation(String connection) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\DefaultCosmosDBServiceFactory.cs:line 59
         at Microsoft.Azure.WebJobs.Extensions.CosmosDB.DefaultCosmosDBServiceFactory.CreateService(String connectionName, CosmosClientOptions cosmosClientOptions) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\DefaultCosmosDBServiceFactory.cs:line 27
         at Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBExtensionConfigProvider.<>c__DisplayClass12_0.<GetService>b__0(String c) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\CosmosDBExtensionConfigProvider.cs:line 114
         at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
         at Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBExtensionConfigProvider.GetService(String connection, String preferredLocations, String userAgent) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\CosmosDBExtensionConfigProvider.cs:line 114
         at Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBTriggerAttributeBindingProvider1.TryCreateAsync(TriggerBindingProviderContext context) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Trigger\CosmosDBTriggerAttributeBindingProvider.cs:line 88
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBTriggerAttributeBindingProvider1.TryCreateAsync(TriggerBindingProviderContext context) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Trigger\CosmosDBTriggerAttributeBindingProvider.cs:line 112
         at Microsoft.Azure.WebJobs.Host.Triggers.CompositeTriggerBindingProvider.TryCreateAsync(TriggerBindingProviderContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\CompositeTriggerBindingProvider.cs:line 22
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 172
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 149
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 157
         at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 85
info: Microsoft.Hosting.Lifetime[0]
      Application is shutting down...
`

#### Repro steps
Program.cs looks like
`
builder.ConfigureServices((hostBuilderCxt, serviceCollection) => serviceCollection.Configure<Microsoft.Azure.WebJobs.Extensions.CosmosDB.CosmosDBOptions>(hostBuilderCxt.Configuration.GetRequiredSection(CosmosDbWebJobOptions.Key)));
`

where CosmosDbWebJobOptions is implements IOptions to override appsettings:
`public class CosmosDbWebJobOptions
{
	public const string Key = "CosmosDB";

	/// <summary>Gets or sets the connection string used to connect to Cosmos DB.</summary>
	public string? Connection { get; set; }

	/// <summary>Gets or sets the name of the Cosmos DB database to use.</summary>
	public string? Database { get; set; }

	/// <summary>Gets or sets the name of the Cosmos DB container name to use.</summary>
	public string? ContainerName { get; set; }
}`

appsettings.json looks like
`"CosmosDB": {
		"Connection": "",
		"Database": "entitysvc",
		"ContainerName": "entities"
  }`

Provide the steps required to reproduce the problem

1. Step A
   In order to bind the options to the trigger; we resolve the these using the following mechanism 
   `config["%Connection%"] = CosmosDbWebJobOptions?.Connection;
    config["%DatabaseName%"]= CosmosDbWebJobOptions?.Database);
    config["%ContainerName%"]= CosmosDbWebJobOptions?.ContainerName);`

#### Expected behavior
The hook should effectively resolve the above config binding via appsettings override; and the trigger should start up.

Provide a description of the expected behavior.

#### Actual behavior
We encounter an exception at web job start up.
Provide a description of the actual behavior observed.
Full execption stack shared above; here's a snippet
`fail: Host.Startup[0]
      Error indexing method 'AdmEntitiesCosmosDBTrigger'
      Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'AdmEntitiesCosmosDBTrigger'
       ---> System.InvalidOperationException: Cannot create container information for %ContainerName% in database %Database% with lease leases in database %Database% : Connection should have an 'accountEndpoint' property or be a string representing a connection string.
       ---> System.InvalidOperationException: Connection should have an 'accountEndpoint' property or be a string representing a connection string.
         at Microsoft.Azure.WebJobs.Extensions.CosmosDB.DefaultCosmosDBServiceFactory.ResolveConnectionInformation(String connection) in C:\azure-webjobs-sdk-extensions\src\WebJobs.Extensions.CosmosDB\Config\DefaultCosmosDBServiceFactory.cs:line 59
`

#### Known workarounds
None. This code works in local testing in VisualStudio.

Provide a description of any known workarounds.

#### Related information 

Provide any related information 

* Package version :
Microsoft.Azure.WebJobs.Extensions; Version="4.0.1"
Microsoft.Azure.WebJobs.Extensions.CosmosDB; Version="4.0.0"

**Comment by ealsur** [comment]
@arafeeq21 What is the Trigger definition? 

Replacement of expressions is done by the Runtime, if the Trigger is defined to use the Expressions, like :

```
[CosmosDBTrigger("%DatabaseName%", "%CollectionName%", Connection = "%Connection%")] IReadOnlyList<dynamic> docs
```

Then the Runtime will attempt to resolve this either from appSettings or the environment looking for the `DatabaseName`, `CollectionName` and `Connection` property.

Your JSON is incorrectly nested and the `Database` property is incorrect.

It should be:

```
{ "Connection": "xxxxxxxx", "DatabaseName": "entitysvc", "ContainerName": "entities" }
```

No `CosmosDB` parent object, because your attribute names within the `%` do not have it. 

We have tests verifying this behavior: https://github.com/Azure/azure-webjobs-sdk-extensions/blob/dev/test/WebJobs.Extensions.CosmosDB.Tests/Trigger/CosmosDBTriggerAttributeBindingProviderTests.cs#L670

**Comment by ealsur** [comment]
@arafeeq21 Is this still an issue? Did the reply help?

**Comment by arafeeq21** [comment]
Using the recommended settings - this has worked.
